package com.enterprisesystem.babysecure.service.impl;

import com.enterprisesystem.babycommon.helpers.SequenceProducerHelper;
import com.enterprisesystem.babysecure.mapper.UserMapper;
import com.enterprisesystem.babysecure.model.dto.UserDto;
import com.enterprisesystem.babysecure.model.entity.UserEntity;
import com.enterprisesystem.babysecure.service.UserService;
import com.enterprisesystem.babycommon.exception.SystemRuntimeException;
import com.enterprisesystem.babycommon.utils.CommonObjectUtil;
import com.enterprisesystem.babycommon.helpers.SHAHelper;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.Date;

/**
 * 用户 Service 实现类
 *
 * @author Generated by Claude Code
 * @date 2026-01-04
 */
@Service
public class UserServiceImpl implements UserService {

    /**
     * 注入 UserMapper
     * 使用 @Resource 注解，按名称注入
     */
    @Resource
    private UserMapper userMapper;

    @Resource
    SequenceProducerHelper sequenceProducerHelper;


    /**
     * 添加用户
     *
     * @param userDto 用户信息
     * @return 返回添加后的用户信息
     */
    @Override
    public UserDto addUser(UserDto userDto) {
        // ==================== 1. 参数预处理 ====================

        // 去除账户前后空格
        userDto.setAccount(CommonObjectUtil.isNull(userDto.getAccount()) ? null : userDto.getAccount().trim());

        // ==================== 2. 基础校验 ====================

        // 校验账号是否为空
        if (StringUtils.isBlank(userDto.getAccount())) {
            throw new SystemRuntimeException(1,"账号不能为空");
        }

        // 校验用户名是否为空
        if (StringUtils.isBlank(userDto.getName())) {
            throw new SystemRuntimeException(2,"用户名不能为空");
        }

        // ==================== 3. 唯一性校验 ====================

        // 检查账号是否已存在
        UserEntity existByAccount = userMapper.selectByAccount(userDto.getAccount());
        if (existByAccount != null) {
            throw new SystemRuntimeException(3,"账号【" + userDto.getAccount() + "】已存在");
        }

        // 如果提供了邮箱，检查邮箱是否已存在
        if (StringUtils.isNotBlank(userDto.getEmail())) {
            UserEntity existByEmail = userMapper.selectByEmail(userDto.getEmail());
            if (existByEmail != null) {
                throw new SystemRuntimeException(4,"邮箱【" + userDto.getEmail() + "】已被使用");
            }
        }

        // 如果提供了手机号，检查手机号是否已存在
        if (StringUtils.isNotBlank(userDto.getTelephone())) {
            UserEntity existByTelephone = userMapper.selectByTelephone(userDto.getTelephone());
            if (existByTelephone != null) {
                throw new SystemRuntimeException(5,"手机号【" + userDto.getTelephone() + "】已被使用");
            }
        }

        // ==================== 4. 密码处理 ====================

        String plainPassword;  // 明文密码

        // 如果未提供密码，自动生成随机密码
        if (StringUtils.isBlank(userDto.getPassword())) {
            // 生成 12 位随机密码（包含大小写字母、数字、特殊字符）
            plainPassword = SHAHelper.getStringRandom(20);
            System.out.println("为用户【" + userDto.getAccount() + "】生成随机密码：" + plainPassword);
        } else {
            // 使用用户提供的密码
            plainPassword = userDto.getPassword();
        }

        // 加密密码（使用 SHA-256）
        String encryptedPassword = SHAHelper.convertByteToHexString(plainPassword);

        // ==================== 5. DTO 转 Entity ====================

        UserEntity entity = new UserEntity();

        // 生成 ID（简单自增，生产环境建议使用雪花算法）
        entity.setId(generateId());

        // 基本信息
        entity.setAccount(userDto.getAccount());
        entity.setName(userDto.getName());
        entity.setPassword(encryptedPassword);  // 存储加密后的密码
        entity.setOriginalPassword(plainPassword); // 存储明文密码
        entity.setEmail(userDto.getEmail());
        entity.setTelephone(userDto.getTelephone());

        // 设置初始状态
        entity.setCStatus(userDto.getStatus() != null ? userDto.getStatus() : 1);  // 默认启用
        entity.setRevision(1);         // 初始版本号
        entity.setLoginFailCount(0);   // 登录失败次数归零

        // 设置时间（如果 DTO 中提供了，使用 DTO 的；否则使用当前时间）
        if (userDto.getPasswordValidDate() != null) {
            entity.setPwdValidDate(new Date(userDto.getPasswordValidDate()));
        }
        if (userDto.getAccountValidData() != null) {
            entity.setAccountValidDate(new Date(userDto.getAccountValidData()));
        }

        // 扩展信息
        entity.setCExtendInfo(userDto.getExtendInfo());
        entity.setCImage(userDto.getImage());

        // ==================== 6. 保存到数据库 ====================

        int result = userMapper.insertBasic(entity);

        // ==================== 7. 处理结果 ====================

        if (result > 0) {
            // 保存成功，将生成的 ID 设置回 DTO
            userDto.setId(entity.getId());

            // 如果是自动生成的密码，可以返回给调用者（用于发送邮件等）
            if (StringUtils.isBlank(userDto.getPassword())) {
                // 可以将明文密码存入临时字段，供上层使用
                // 注意：不要在日志或响应中直接返回明文密码
                userDto.setPassword("******");  // 隐藏密码
                // 实际项目中应该通过邮件等方式发送密码
            }

            return userDto;
        } else {
            throw new SystemRuntimeException(66,"添加用户失败，请稍后重试");
        }
    }

    private Integer generateId() {
        return (int) sequenceProducerHelper.getUniqueSequence();
    }

    // ==================== 工具方法 ====================

    /**
     * Entity 转换为 DTO
     *
     * @param entity 实体对象
     * @return DTO 对象
     */
    private UserDto entityToDto(UserEntity entity) {
        if (entity == null) {
            return null;
        }
        UserDto dto = new UserDto();
        dto.setId(entity.getId());
        dto.setAccount(entity.getAccount());
        dto.setName(entity.getName());
        dto.setEmail(entity.getEmail());
        dto.setTelephone(entity.getTelephone());
        dto.setStatus(entity.getCStatus());
        dto.setLoginFailCount(entity.getLoginFailCount());
        dto.setRevision(entity.getRevision());
        dto.setExtendInfo(entity.getCExtendInfo());
        dto.setImage(entity.getCImage());

        // 时间转换（Date 转 Long）
        if (entity.getPwdValidDate() != null) {
            dto.setPasswordValidDate(entity.getPwdValidDate().getTime());
        }
        if (entity.getAccountValidDate() != null) {
            dto.setAccountValidData(entity.getAccountValidDate().getTime());
        }

        return dto;
    }

    /**
     * DTO 转换为 Entity
     *
     * @param dto DTO 对象
     * @return 实体对象
     */
    private UserEntity dtoToEntity(UserDto dto) {
        if (dto == null) {
            return null;
        }
        UserEntity entity = new UserEntity();
        entity.setId(dto.getId());
        entity.setAccount(dto.getAccount());
        entity.setName(dto.getName());
        entity.setEmail(dto.getEmail());
        entity.setTelephone(dto.getTelephone());
        entity.setCStatus(dto.getStatus());
        entity.setLoginFailCount(dto.getLoginFailCount());
        entity.setRevision(dto.getRevision());
        entity.setCExtendInfo(dto.getExtendInfo());
        entity.setCImage(dto.getImage());

        // 时间转换（Long 转 Date）
        if (dto.getPasswordValidDate() != null) {
            entity.setPwdValidDate(new Date(dto.getPasswordValidDate()));
        }
        if (dto.getAccountValidData() != null) {
            entity.setAccountValidDate(new Date(dto.getAccountValidData()));
        }

        return entity;
    }
}
