-- 创建 seller 表
CREATE TABLE IF NOT EXISTS seller (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE COMMENT '商家代码',
    name VARCHAR(100) NOT NULL COMMENT '商家名称',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家表';

-- 插入初始数据
--INSERT INTO seller (code, name) VALUES ('SELLER001', '测试商家1');
--INSERT INTO seller (code, name) VALUES ('SELLER002', '测试商家2');
