package com.enterprisesystem.babycommon.aspect;

import com.enterprisesystem.babycommon.annotation.ApiExceptionHandler;
import com.enterprisesystem.babycommon.entity.APIResult;
import com.enterprisesystem.babycommon.exception.SystemRuntimeException;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.Signature;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.aspectj.lang.reflect.MethodSignature;
import org.springframework.stereotype.Component;

/**
 * API 异常处理切面
 *
 * 【作用】
 * 拦截所有带有 @ApiExceptionHandler 注解的方法，在方法执行前后进行处理
 *
 * 【使用方法】
 * 在 Controller 方法上添加 @ApiExceptionHandler 注解即可
 *
 * @author Generated by Claude Code
 * @date 2026-01-04
 */
@Aspect
@Component  // ✅ 让 Spring 管理这个切面
public class ApiExceptionAspect {

    /**
     * 定义切点：匹配带有 @ApiExceptionHandler 注解的方法
     */
    @Pointcut("@annotation(com.enterprisesystem.babycommon.annotation.ApiExceptionHandler)")
    public void apiPointcut(){}

    private boolean support(ProceedingJoinPoint pjp){
        Class<?> returnType = getReturnType(pjp);
        return returnType != null && APIResult.class.isAssignableFrom(returnType);
    }

    private Class<?> getReturnType(ProceedingJoinPoint pjp){
        Signature signature = pjp.getSignature();
        if(signature instanceof MethodSignature){
            return ((MethodSignature)signature).getReturnType();
        }
        return null;
    }

    /**
     * 环绕通知：拦截 API 方法
     *
     * @param joinPoint 连接点，可以获取目标方法信息
     * @return 目标方法的返回值
     * @throws Throwable 可抛出异常
     */
    @Around(value = "apiPointcut() && @annotation(annon)")
    public Object handleException(ProceedingJoinPoint joinPoint,ApiExceptionHandler annon) throws Throwable {
        System.out.println("✅ 成功进入切面方法！");
        // 该切面仅支持 v1-v3的接口
        if(!support(joinPoint)){
            return joinPoint.proceed();
        }

        APIResult apiResult = new APIResult();
        long start = 0;
        try {
            start = System.nanoTime();
            apiResult = (APIResult)joinPoint.proceed();
            double elapsed = (System.nanoTime() - start) / 1e6;
            apiResult.setApiId(annon.apiId());
            apiResult.setElapsed(elapsed);
        } catch(SystemRuntimeException e) {
            double elapsed = (System.nanoTime() - start) / 1e6;// 计算调用耗时
            apiResult.setElapsed(elapsed);
            apiResult.setErrorCode(e.getErrorCode());
            apiResult.setApiId(annon.apiId());
            apiResult.setErrorInfo(e.getOrignMessage());
        }
        return apiResult;
    }
}
