package com.enterprisesystem.babycommon.aspect;

import com.enterprisesystem.babycommon.annotation.ApiExceptionHandler;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Pointcut;
import org.springframework.stereotype.Component;

/**
 * API 异常处理切面
 *
 * 【作用】
 * 拦截所有带有 @ApiExceptionHandler 注解的方法，在方法执行前后进行处理
 *
 * 【使用方法】
 * 在 Controller 方法上添加 @ApiExceptionHandler 注解即可
 *
 * @author Generated by Claude Code
 * @date 2026-01-04
 */
@Aspect
@Component  // ✅ 让 Spring 管理这个切面
public class ApiExceptionAspect {

    /**
     * 定义切点：匹配带有 @ApiExceptionHandler 注解的方法
     */
    @Pointcut("@annotation(com.enterprisesystem.babycommon.annotation.ApiExceptionHandler)")
    public void apiPointcut(){}

    /**
     * 环绕通知：拦截 API 方法
     *
     * @param joinPoint 连接点，可以获取目标方法信息
     * @return 目标方法的返回值
     * @throws Throwable 可抛出异常
     */
    @Around(value = "apiPointcut()")
    public Object handleException(ProceedingJoinPoint joinPoint) throws Throwable {
        // ✅ 获取目标方法信息
        String methodName = joinPoint.getSignature().getName();
        String className = joinPoint.getTarget().getClass().getSimpleName();

        System.out.println("✅ 成功进入切面方法！");
        System.out.println("   目标类：" + className);
        System.out.println("   目标方法：" + methodName);

        try {
            // ✅ 执行目标方法（必须调用，否则目标方法不会执行）
            Object result = joinPoint.proceed();

            System.out.println("   方法执行成功，返回值：" + result);

            return result;

        } catch (Exception e) {
            System.err.println("   方法执行异常：" + e.getMessage());

            // 可以在这里记录日志、发送告警等
            throw e;
        }
    }
}
