package com.enterprisesystem.babysecure.model.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 系统授权表实体类
 * 对应数据库表：baby_license
 *
 * @author Generated by Claude Code
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LicenseEntity {

    /**
     * 主键ID
     * 数据库字段：c_id INT(11) PRIMARY KEY AUTO_INCREMENT
     */
    private Integer cId;

    /**
     * 系统名称
     * 数据库字段：c_system VARCHAR(255) NOT NULL COMMENT '系统名称'
     */
    private String cSystem;

    /**
     * 唯一授权ID
     * 数据库字段：c_key VARCHAR(255) NOT NULL COMMENT '唯一授权ID'
     */
    private String cKey;

    /**
     * 文件内容
     * 数据库字段：c_license TEXT COMMENT '文件内容'
     */
    private String cLicense;

}