package com.enterprisesystem.babysecure.mapper;

import com.enterprisesystem.babycommon.mapper.BaseMapper;
import com.enterprisesystem.babysecure.model.entity.LicenseEntity;
import org.apache.ibatis.annotations.*;
import java.util.List;

/**
 * 系统授权表Mapper接口
 * 对应数据库表：baby_license
 *
 * @author Generated by Claude Code
 */
@Mapper
public interface LicenseMapper extends BaseMapper<LicenseEntity, Integer> {

    /**
     * 插入授权记录
     *
     * @param entity 授权实体
     * @return 影响行数
     */
    @Override
    @Insert("INSERT INTO baby_license(c_system, c_key, c_license) " +
            "VALUES(#{cSystem}, #{cKey}, #{cLicense})")
    @Options(useGeneratedKeys = true, keyProperty = "cId")
    int insert(LicenseEntity entity);

    /**
     * 批量插入授权记录
     *
     * @param entities 授权实体列表
     * @return 影响行数
     */
    @Override
    @Insert("<script>" +
            "INSERT INTO baby_license(c_system, c_key, c_license) VALUES " +
            "<foreach collection='list' item='item' separator=','>" +
            "(#{item.cSystem}, #{item.cKey}, #{item.cLicense})" +
            "</foreach>" +
            "</script>")
    int batchInsert(@Param("list") List<LicenseEntity> entities);

    /**
     * 更新授权记录
     *
     * @param entity 授权实体
     * @return 影响行数
     */
    @Override
    @Update("UPDATE baby_license SET " +
            "c_system = #{cSystem}, " +
            "c_key = #{cKey}, " +
            "c_license = #{cLicense} " +
            "WHERE c_id = #{cId}")
    int update(LicenseEntity entity);

    /**
     * 根据主键删除授权记录
     *
     * @param id 主键ID
     * @return 影响行数
     */
    @Override
    @Delete("DELETE FROM baby_license WHERE c_id = #{id}")
    int deleteById(@Param("id") Integer id);

    /**
     * 根据主键查询授权记录
     *
     * @param id 主键ID
     * @return 授权实体
     */
    @Override
    @Select("SELECT c_id, c_system, c_key, c_license FROM baby_license WHERE c_id = #{id}")
    @Results({
            @Result(property = "cId", column = "c_id"),
            @Result(property = "cSystem", column = "c_system"),
            @Result(property = "cKey", column = "c_key"),
            @Result(property = "cLicense", column = "c_license")
    })
    LicenseEntity selectById(@Param("id") Integer id);

    /**
     * 查询所有授权记录
     *
     * @return 授权实体列表
     */
    @Override
    @Select("SELECT c_id, c_system, c_key, c_license FROM baby_license ORDER BY c_id DESC")
    @Results({
            @Result(property = "cId", column = "c_id"),
            @Result(property = "cSystem", column = "c_system"),
            @Result(property = "cKey", column = "c_key"),
            @Result(property = "cLicense", column = "c_license")
    })
    List<LicenseEntity> selectAll();

    /**
     * 统计授权记录总数
     *
     * @return 记录总数
     */
    @Override
    @Select("SELECT COUNT(*) FROM baby_license")
    Long count();

    /**
     * 根据系统名称查询授权记录
     *
     * @param systemName 系统名称
     * @return 授权实体列表
     */
    @Select("SELECT c_id, c_system, c_key, c_license FROM baby_license WHERE c_system = #{systemName}")
    @Results({
            @Result(property = "cId", column = "c_id"),
            @Result(property = "cSystem", column = "c_system"),
            @Result(property = "cKey", column = "c_key"),
            @Result(property = "cLicense", column = "c_license")
    })
    List<LicenseEntity> selectBySystem(@Param("systemName") String systemName);

    /**
     * 根据授权Key查询授权记录
     *
     * @param licenseKey 授权Key
     * @return 授权实体
     */
    @Select("SELECT c_id, c_system, c_key, c_license FROM baby_license WHERE c_key = #{licenseKey}")
    @Results({
            @Result(property = "cId", column = "c_id"),
            @Result(property = "cSystem", column = "c_system"),
            @Result(property = "cKey", column = "c_key"),
            @Result(property = "cLicense", column = "c_license")
    })
    LicenseEntity selectByKey(@Param("licenseKey") String licenseKey);


}