package com.enterprisesystem.babysecure.mapper;

import com.enterprisesystem.babycommon.query.LambdaQueryWrapper;
import com.enterprisesystem.babysecure.model.entity.UserEntity;
import org.apache.ibatis.annotations.*;

import java.util.List;

/**
 * 用户 Mapper 接口
 * 对应数据库表：b_user
 *
 * 【Mapper 接口说明】
 * - Mapper 是一个接口，MyBatis 会自动生成实现类
 * - 使用 @Mapper 注解标记，Spring Boot 启动时自动扫描注册
 * - 通过 @Select、@Insert、@Update、@Delete 注解直接编写 SQL
 *
 * @author Generated by Claude Code
 * @date 2026-01-04
 */
@Mapper
public interface UserMapper {

    // ==================== 基础查询操作 ====================

    /**
     * 查询所有用户
     *
     * @return 所有用户列表
     */
    @Select("SELECT * FROM b_user")
    List<UserEntity> selectAll();

    /**
     * 根据 ID 查询用户
     *
     * @param id 用户ID
     * @return 用户实体对象
     */
    @Select("SELECT * FROM b_user WHERE id = #{id}")
    UserEntity selectById(@Param("id") Integer id);

    /**
     * 根据账号查询用户
     *
     * 应用场景：用户登录时，通过账号查询用户信息
     *
     * @param account 账号
     * @return 用户实体对象
     */
    @Select("SELECT * FROM b_user WHERE account = #{account}")
    UserEntity selectByAccount(@Param("account") String account);

    /**
     * 根据邮箱查询用户
     *
     * 应用场景：用户通过邮箱登录或找回密码
     *
     * @param email 邮箱地址
     * @return 用户实体对象
     */
    @Select("SELECT * FROM b_user WHERE email = #{email}")
    UserEntity selectByEmail(@Param("email") String email);

    /**
     * 根据手机号查询用户
     *
     * 应用场景：用户通过手机号登录或验证
     *
     * @param telephone 手机号
     * @return 用户实体对象
     */
    @Select("SELECT * FROM b_user WHERE telephone = #{telephone}")
    UserEntity selectByTelephone(@Param("telephone") String telephone);

    /**
     * 根据状态查询用户列表
     *
     * 应用场景：查询所有正常用户、所有禁用用户等
     *
     * @param cStatus 用户状态（1-正常，0-禁用，2-锁定）
     * @return 用户列表
     */
    @Select("SELECT * FROM b_user WHERE c_status = #{cStatus}")
    List<UserEntity> selectByStatus(@Param("cStatus") Integer cStatus);

    /**
     * 根据账号或邮箱查询用户
     *
     * 应用场景：支持用户使用账号或邮箱登录
     *
     * @param account 账号或邮箱
     * @return 用户实体对象
     */
    @Select("SELECT * FROM b_user WHERE account = #{account} OR email = #{account}")
    UserEntity selectByAccountOrEmail(@Param("account") String account);

    // ==================== 条件查询（支持动态 SQL）====================

    /**
     * 使用 LambdaQueryWrapper 动态查询用户列表
     *
     * 应用场景：复杂的动态条件查询，如搜索用户
     *
     * 使用示例：
     * LambdaQueryWrapper<UserEntity> wrapper = new LambdaQueryWrapper<>();
     * wrapper.like(UserEntity::getAccount, "zhang")
     *        .eq(UserEntity::getCStatus, 1)
     *        .orderByDesc(UserEntity::getId);
     * List<UserEntity> users = userMapper.selectByWrapper(wrapper);
     *
     * @param wrapper Lambda 查询构造器
     * @return 用户列表
     */
    @Select("SELECT * FROM b_user ${wrapper.sql}")
    List<UserEntity> selectByWrapper(@Param("wrapper") LambdaQueryWrapper<UserEntity> wrapper);

    /**
     * 根据条件查询单个用户
     *
     * 应用场景：根据多个条件精确查询一个用户
     *
     * @param entity 查询条件实体（非 null 字段作为查询条件）
     * @return 用户实体对象
     */
    @Select("<script>" +
            "SELECT * FROM b_user " +
            "WHERE 1=1 " +
            "<if test='id != null'>AND id = #{id}</if> " +
            "<if test='account != null'>AND account = #{account}</if> " +
            "<if test='name != null'>AND name = #{name}</if> " +
            "<if test='email != null'>AND email = #{email}</if> " +
            "<if test='telephone != null'>AND telephone = #{telephone}</if> " +
            "<if test='cStatus != null'>AND c_status = #{cStatus}</if> " +
            "LIMIT 1" +
            "</script>")
    UserEntity selectOne(UserEntity entity);

    // ==================== 插入操作 ====================

    /**
     * 插入用户（完整插入）
     *
     * 注意：b_user 表的 id 字段不是自增的，需要手动生成 ID
     * 建议使用雪花算法或 UUID 生成器
     *
     * @param entity 用户实体对象
     * @return 影响的行数
     */
    @Insert("INSERT INTO b_user(id, account, name, password, email, telephone, " +
            "pwd_valid_date, c_status, login_fail_count, pwd_log, revision, " +
            "uuid, c_extend_info, account_valid_date, signature_pwd, " +
            "c_image, c_signture_pwd_valid_date, c_signture_pwd_log, c_his_uuid) " +
            "VALUES(#{id}, #{account}, #{name}, #{password}, #{email}, #{telephone}, " +
            "#{pwdValidDate}, #{cStatus}, #{loginFailCount}, #{pwdLog}, #{revision}, " +
            "#{uuid}, #{cExtendInfo}, #{accountValidDate}, #{signaturePwd}, " +
            "#{cImage}, #{cSignturePwdValidDate}, #{cSignturePwdLog}, #{cHisUuid})")
    int insert(UserEntity entity);

    /**
     * 插入用户（基础字段）
     *
     * 应用场景：创建新用户，只插入必要字段
     *
     * @param entity 用户实体对象
     * @return 影响的行数
     */
    @Insert("INSERT INTO b_user(id, account, name, password, email, telephone, c_status, revision) " +
            "VALUES(#{id}, #{account}, #{name}, #{password}, #{email}, #{telephone}, #{cStatus}, #{revision})")
    int insertBasic(UserEntity entity);

    /**
     * 选择性插入用户（只插入非空字段）
     *
     * 应用场景：灵活插入，只设置需要的字段
     *
     * @param entity 用户实体对象
     * @return 影响的行数
     */
    @Insert("<script>" +
            "INSERT INTO b_user " +
            "<trim prefix='(' suffix=')' suffixOverrides=','>" +
            "<if test='id != null'>id,</if>" +
            "<if test='account != null'>account,</if>" +
            "<if test='name != null'>name,</if>" +
            "<if test='password != null'>password,</if>" +
            "<if test='email != null'>email,</if>" +
            "<if test='telephone != null'>telephone,</if>" +
            "<if test='cStatus != null'>c_status,</if>" +
            "<if test='revision != null'>revision,</if>" +
            "</trim>" +
            "<trim prefix='VALUES (' suffix=')' suffixOverrides=','>" +
            "<if test='id != null'>#{id},</if>" +
            "<if test='account != null'>#{account},</if>" +
            "<if test='name != null'>#{name},</if>" +
            "<if test='password != null'>#{password},</if>" +
            "<if test='email != null'>#{email},</if>" +
            "<if test='telephone != null'>#{telephone},</if>" +
            "<if test='cStatus != null'>#{cStatus},</if>" +
            "<if test='revision != null'>#{revision},</if>" +
            "</trim>" +
            "</script>")
    int insertSelective(UserEntity entity);

    // ==================== 更新操作 ====================

    /**
     * 更新用户信息（完整更新）
     *
     * @param entity 用户实体对象（必须包含 id）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET " +
            "account = #{account}, " +
            "name = #{name}, " +
            "password = #{password}, " +
            "email = #{email}, " +
            "telephone = #{telephone}, " +
            "pwd_valid_date = #{pwdValidDate}, " +
            "c_status = #{cStatus}, " +
            "login_fail_count = #{loginFailCount}, " +
            "pwd_log = #{pwdLog}, " +
            "revision = #{revision}, " +
            "c_extend_info = #{cExtendInfo}, " +
            "account_valid_date = #{accountValidDate}, " +
            "signature_pwd = #{signaturePwd}, " +
            "c_image = #{cImage}, " +
            "c_signture_pwd_valid_date = #{cSignturePwdValidDate}, " +
            "c_signture_pwd_log = #{cSignturePwdLog}, " +
            "c_his_uuid = #{cHisUuid} " +
            "WHERE id = #{id}")
    int update(UserEntity entity);

    /**
     * 选择性更新用户（只更新非空字段）
     *
     * 应用场景：只想更新部分字段，其他字段保持不变
     *
     * @param entity 用户实体对象（必须包含 id）
     * @return 影响的行数
     */
    @Update("<script>" +
            "UPDATE b_user " +
            "<set>" +
            "<if test='account != null'>account = #{account},</if>" +
            "<if test='name != null'>name = #{name},</if>" +
            "<if test='password != null'>password = #{password},</if>" +
            "<if test='email != null'>email = #{email},</if>" +
            "<if test='telephone != null'>telephone = #{telephone},</if>" +
            "<if test='pwdValidDate != null'>pwd_valid_date = #{pwdValidDate},</if>" +
            "<if test='cStatus != null'>c_status = #{cStatus},</if>" +
            "<if test='loginFailCount != null'>login_fail_count = #{loginFailCount},</if>" +
            "<if test='pwdLog != null'>pwd_log = #{pwdLog},</if>" +
            "<if test='revision != null'>revision = #{revision},</if>" +
            "<if test='cExtendInfo != null'>c_extend_info = #{cExtendInfo},</if>" +
            "<if test='accountValidDate != null'>account_valid_date = #{accountValidDate},</if>" +
            "<if test='signaturePwd != null'>signature_pwd = #{signaturePwd},</if>" +
            "<if test='cImage != null'>c_image = #{cImage},</if>" +
            "<if test='cSignturePwdValidDate != null'>c_signture_pwd_valid_date = #{cSignturePwdValidDate},</if>" +
            "<if test='cSignturePwdLog != null'>c_signture_pwd_log = #{cSignturePwdLog},</if>" +
            "<if test='cHisUuid != null'>c_his_uuid = #{cHisUuid},</if>" +
            "</set>" +
            "WHERE id = #{id}" +
            "</script>")
    int updateSelective(UserEntity entity);

    /**
     * 更新用户密码
     *
     * 应用场景：用户修改密码或管理员重置密码
     *
     * @param id 用户ID
     * @param password 新密码（加密后的）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET password = #{password} WHERE id = #{id}")
    int updatePassword(@Param("id") Integer id, @Param("password") String password);

    /**
     * 更新用户状态
     *
     * 应用场景：启用/禁用用户账户
     *
     * @param id 用户ID
     * @param cStatus 新状态（1-正常，0-禁用，2-锁定）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET c_status = #{cStatus} WHERE id = #{id}")
    int updateStatus(@Param("id") Integer id, @Param("cStatus") Integer cStatus);

    /**
     * 更新登录失败次数
     *
     * 应用场景：登录失败时增加计数，登录成功时重置为 0
     *
     * @param id 用户ID
     * @param loginFailCount 登录失败次数
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET login_fail_count = #{loginFailCount} WHERE id = #{id}")
    int updateLoginFailCount(@Param("id") Integer id, @Param("loginFailCount") Integer loginFailCount);

    /**
     * 更新密码修改日志
     *
     * 应用场景：记录密码修改历史，防止重复使用旧密码
     *
     * @param id 用户ID
     * @param pwdLog 密码修改日志（JSON 格式）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET pwd_log = #{pwdLog} WHERE id = #{id}")
    int updatePwdLog(@Param("id") Integer id, @Param("pwdLog") String pwdLog);

    /**
     * 更新扩展信息
     *
     * 应用场景：更新用户的额外业务属性（JSON 格式）
     *
     * @param id 用户ID
     * @param cExtendInfo 扩展信息（JSON 格式）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET c_extend_info = #{cExtendInfo} WHERE id = #{id}")
    int updateExtendInfo(@Param("id") Integer id, @Param("cExtendInfo") String cExtendInfo);

    /**
     * 更新头像
     *
     * @param id 用户ID
     * @param cImage 头像（Base64 或 URL）
     * @return 影响的行数
     */
    @Update("UPDATE b_user SET c_image = #{cImage} WHERE id = #{id}")
    int updateImage(@Param("id") Integer id, @Param("cImage") String cImage);

    /**
     * 乐观锁更新（带版本号控制）
     *
     * 应用场景：防止并发修改冲突
     * 只有当数据库中的 revision 值与传入的 revision 值相等时才更新
     *
     * @param entity 用户实体对象（必须包含 id 和 revision）
     * @return 影响的行数（0 表示版本冲突，1 表示成功）
     */
    @Update("UPDATE b_user SET " +
            "name = #{name}, " +
            "email = #{email}, " +
            "telephone = #{telephone}, " +
            "c_status = #{cStatus}, " +
            "revision = revision + 1 " +
            "WHERE id = #{id} AND revision = #{revision}")
    int updateWithVersion(UserEntity entity);

    // ==================== 删除操作 ====================

    /**
     * 根据 ID 删除用户
     *
     * ⚠️ 注意：实际开发中建议使用软删除（更新状态为删除），而非物理删除
     *
     * @param id 用户ID
     * @return 影响的行数
     */
    @Delete("DELETE FROM b_user WHERE id = #{id}")
    int deleteById(@Param("id") Integer id);

    /**
     * 批量删除用户
     *
     * @param ids 用户ID列表
     * @return 影响的行数
     */
    @Delete("<script>" +
            "DELETE FROM b_user WHERE id IN " +
            "<foreach collection='ids' item='id' open='(' separator=',' close=')'>" +
            "#{id}" +
            "</foreach>" +
            "</script>")
    int deleteByIds(@Param("ids") List<Integer> ids);

    // ==================== 统计查询 ====================

    /**
     * 统计用户总数
     *
     * @return 用户总数
     */
    @Select("SELECT COUNT(*) FROM b_user")
    Long count();

    /**
     * 根据状态统计用户数量
     *
     * @param cStatus 用户状态
     * @return 用户数量
     */
    @Select("SELECT COUNT(*) FROM b_user WHERE c_status = #{cStatus}")
    Long countByStatus(@Param("cStatus") Integer cStatus);

    /**
     * 根据账号统计数量（用于检查账号是否已存在）
     *
     * @param account 账号
     * @return 数量（0-不存在，1-已存在）
     */
    @Select("SELECT COUNT(*) FROM b_user WHERE account = #{account}")
    Long countByAccount(@Param("account") String account);

    /**
     * 根据邮箱统计数量（用于检查邮箱是否已存在）
     *
     * @param email 邮箱
     * @return 数量（0-不存在，1-已存在）
     */
    @Select("SELECT COUNT(*) FROM b_user WHERE email = #{email}")
    Long countByEmail(@Param("email") String email);

    /**
     * 使用 LambdaQueryWrapper 统计用户数量
     *
     * @param wrapper Lambda 查询构造器
     * @return 用户数量
     */
    @Select("SELECT COUNT(*) FROM b_user ${wrapper.sql}")
    Long countByWrapper(@Param("wrapper") LambdaQueryWrapper<UserEntity> wrapper);

    // ==================== 辅助查询方法 ====================

    /**
     * 检查用户是否存在
     *
     * @param id 用户ID
     * @return true-存在，false-不存在
     */
    @Select("SELECT COUNT(*) > 0 FROM b_user WHERE id = #{id}")
    boolean existsById(@Param("id") Integer id);

    /**
     * 检查账号是否存在
     *
     * @param account 账号
     * @return true-已存在，false-不存在
     */
    @Select("SELECT COUNT(*) > 0 FROM b_user WHERE account = #{account}")
    boolean existsByAccount(@Param("account") String account);

    /**
     * 检查邮箱是否存在
     *
     * @param email 邮箱
     * @return true-已存在，false-不存在
     */
    @Select("SELECT COUNT(*) > 0 FROM b_user WHERE email = #{email}")
    boolean existsByEmail(@Param("email") String email);
}
