package com.enterprisesystem.babysecure.shiro.config;

import org.apache.shiro.authc.AuthenticationToken;

/**
 * JWT Token 认证令牌
 *
 * 【功能说明】
 * 实现 Shiro 的 AuthenticationToken 接口，用于 JWT 认证
 *
 * 【字段说明】
 * - principal：用户身份标识（通常是用户账号）
 * - credentials：用户凭证（JWT Token 字符串）
 *
 * @author Generated by Claude Code
 * @date 2026-01-05
 */
public class JwtToken implements AuthenticationToken {

    /**
     * 用户身份标识（账号）
     */
    private Object principal;

    /**
     * JWT Token 字符串
     */
    private Object credentials;

    /**
     * 构造函数 1：只传入 Token（兼容旧代码）
     * 此时 principal 和 credentials 都是 token
     *
     * @param token JWT Token 字符串
     */
    public JwtToken(String token) {
        this.principal = token;
        this.credentials = token;
    }

    /**
     * 构造函数 2：传入账号和 Token（推荐使用）
     * 此时 principal 是账号，credentials 是 token
     *
     * @param token  JWT Token 字符串
     * @param account 用户账号
     */
    public JwtToken(String token, String account) {
        this.principal = account;
        this.credentials = token;
    }

    /**
     * 获取用户身份标识（账号）
     *
     * @return 用户账号
     */
    @Override
    public Object getPrincipal() {
        return principal;
    }

    /**
     * 获取用户凭证（JWT Token）
     *
     * @return JWT Token 字符串
     */
    @Override
    public Object getCredentials() {
        return credentials;
    }
}
